# Generated by Django 3.1 on 2021-04-24 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to='images\\')),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
                ('background', models.CharField(choices=[('#0a4b94', 'Blueberry'), ('#DAA520D9', 'Butter'), ('#95001bE6', 'Candy'), ('#463f85', 'Grape'), ('#009342', 'Kivi'), ('#930051', 'Onion'), ('', 'None')], default='', max_length=20)),
                ('doc_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
