# Generated by Django 3.1 on 2021-04-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypost',
            name='head',
            field=models.CharField(default='Unknown', max_length=32),
        ),
    ]
