# Generated by Django 3.1 on 2021-04-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20210425_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='doc',
            field=models.FileField(upload_to='pdf\\'),
        ),
        migrations.DeleteModel(
            name='MyPage',
        ),
    ]
